'use server'

import { createClient, createAdminClient } from '@/lib/supabase/server'

export type UpdateProfileResult = { success: true } | { success: false; error: string }

export async function updateAffiliateProfile(formData: FormData): Promise<UpdateProfileResult> {
  const supabase = createClient()
  const admin = createAdminClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Not authenticated' }

  const displayName   = (formData.get('display_name') as string)?.trim() || null
  const bio           = (formData.get('bio') as string)?.trim() || null
  const payoutEmail   = (formData.get('payout_email') as string)?.trim() || user.email
  const nicheTags     = formData.getAll('niche_tags') as string[]
  const vineyardPublic = formData.get('vineyard_public') === 'true'

  const { error } = await admin
    .from('affiliate_profiles')
    .update({ display_name: displayName, bio, payout_email: payoutEmail, niche_tags: nicheTags, vineyard_public: vineyardPublic })
    .eq('user_id', user.id)

  if (error) return { success: false, error: error.message }
  return { success: true }
}

export type GenerateLinkResult =
  | { success: true; token: string }
  | { success: false; error: string }

export async function generateReferralLink(jobId: string): Promise<GenerateLinkResult> {
  const supabase = createClient()
  const admin = createAdminClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Not authenticated' }

  // Get or create affiliate profile
  let { data: profile } = await admin
    .from('affiliate_profiles')
    .select('id')
    .eq('user_id', user.id)
    .single()

  if (!profile) {
    const { data: newProfile, error: profileError } = await admin
      .from('affiliate_profiles')
      .insert({ user_id: user.id, payout_email: user.email })
      .select('id')
      .single()
    if (profileError) return { success: false, error: profileError.message }
    profile = newProfile
  }

  // Return existing link if one already exists for this job
  const { data: existing } = await admin
    .from('referral_links')
    .select('token')
    .eq('affiliate_id', profile.id)
    .eq('job_id', jobId)
    .single()

  if (existing) return { success: true, token: existing.token }

  // Create new link (token is auto-generated by DB default)
  const { data: link, error: linkError } = await admin
    .from('referral_links')
    .insert({ affiliate_id: profile.id, job_id: jobId })
    .select('token')
    .single()

  if (linkError) return { success: false, error: linkError.message }
  return { success: true, token: link.token }
}
