'use server'

import { createActionClient, createAdminClient } from '@/lib/supabase/server'

export type UpdateProfileResult = { success: true } | { success: false; error: string }

export async function updateAffiliateProfile(formData: FormData): Promise<UpdateProfileResult> {
  const supabase = createActionClient()
  const admin = createAdminClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Not authenticated' }

  const displayName    = (formData.get('display_name') as string)?.trim() || null
  const bio            = (formData.get('bio') as string)?.trim() || null
  const payoutEmail    = (formData.get('payout_email') as string)?.trim() || user.email
  const nicheTags      = formData.getAll('niche_tags') as string[]
  const vineyardPublic = formData.get('vineyard_public') === 'true'

  const { error } = await admin
    .from('affiliate_profiles')
    .update({ display_name: displayName, bio, payout_email: payoutEmail, niche_tags: nicheTags, vineyard_public: vineyardPublic })
    .eq('user_id', user.id)

  if (error) return { success: false, error: error.message }
  return { success: true }
}

export type GenerateLinkResult =
  | { success: true; token: string }
  | { success: false; error: string }

export async function generateReferralLink(jobId: string): Promise<GenerateLinkResult> {
  const supabase = createActionClient()
  const admin = createAdminClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Not authenticated' }

  // Get or create affiliate profile
  let { data: profile } = await admin
    .from('affiliate_profiles')
    .select('id')
    .eq('user_id', user.id)
    .single()

  if (!profile) {
    const { data: newProfile, error: profileError } = await admin
      .from('affiliate_profiles')
      .insert({ user_id: user.id, payout_email: user.email })
      .select('id')
      .single()
    if (profileError) return { success: false, error: profileError.message }
    profile = newProfile
  }

  // Return existing link if one already exists for this job
  const { data: existing } = await admin
    .from('referral_links')
    .select('token')
    .eq('affiliate_id', profile.id)
    .eq('job_id', jobId)
    .single()

  if (existing) {
    // Ensure a vineyard listing exists for this job
    await ensureVineyardListing(admin, profile.id, jobId)
    return { success: true, token: existing.token }
  }

  // Create new link (token is auto-generated by DB default)
  const { data: link, error: linkError } = await admin
    .from('referral_links')
    .insert({ affiliate_id: profile.id, job_id: jobId })
    .select('token')
    .single()

  if (linkError) return { success: false, error: linkError.message }

  // Auto-add to vineyard (active by default)
  await ensureVineyardListing(admin, profile.id, jobId)

  return { success: true, token: link.token }
}

async function ensureVineyardListing(admin: ReturnType<typeof createAdminClient>, affiliateId: string, jobId: string) {
  const { data: existing } = await admin
    .from('vineyard_listings')
    .select('id')
    .eq('affiliate_id', affiliateId)
    .eq('job_id', jobId)
    .maybeSingle()

  if (existing) return

  const { data: last } = await admin
    .from('vineyard_listings')
    .select('sort_order')
    .eq('affiliate_id', affiliateId)
    .order('sort_order', { ascending: false })
    .limit(1)
    .maybeSingle()

  await admin.from('vineyard_listings').insert({
    affiliate_id: affiliateId,
    job_id: jobId,
    active: true,
    sort_order: (last?.sort_order ?? -1) + 1,
  })
}
